### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by fdixonb** [openpnp/openpnp-openbuilds#10]
Following the steps for Configuration at the end of this webpage gives an error, after downloading and saving the machine.xml file to the .openpnp2 directory
https://github.com/openpnp/openpnp-openbuilds/wiki/Build-Instructions

Configuration load error.  Element nozzle-tips does not have a match in ...

The xml file looks fine to me so not sure if this is an openpnp issue or not.

![image](https://user-images.githubusercontent.com/71485057/93562627-c1008180-f9c9-11ea-9a51-6847a8d826e6.png)

**Comment by vonnieda** [comment]
The config posted there has become outdated and is no longer compatible with the current code. I'd recommend just following the configuration guide at https://github.com/openpnp/openpnp/wiki/Setup-and-Calibration instead, and you can use the old config as a reference if needed.
