### ISSUE TITLE
BOM update

### ISSUE THREAD

**Issue by byrek** [openpnp/openpnp-openbuilds#9]
Howdy,
I have just received a mechanical set from OpenBuilds store. Parts were ordered using BOM list. There are some issues that may be updated:
- row 5 (M5x10 Low Profile SCHS) are way too long, they should be M5x6 Low Profile SCHS with a following link http://openbuildspartstore.com/low-profile-screws-m5-30-pack/
- row 22, 44, 69 (M5x30 Low Profile SCHS) are too short, they should be at least 32mm to catch the thread,so 35mm is fine; link http://openbuildspartstore.com/low-profile-screws-m5/
I will keep You updated, brgds, Mike

**Comment by vonnieda** [comment]
Thanks @byrek , appreciate the updates! I've updated the BOM.
